Numpy?
Numerical Python.
Python에서 대규모 다차원 배열을
다룰 수 있게 도와주는 라이브러리

Why?
데이터의 대부분은 숫자 배열로 볼 수 있다.

Python list?
파이썬 리스트로도 계산 할 수 있지만
numpy는 list에 비해서 빠른 연산을 지원하고
메모리를 효율적으로 사용한다

배열 만들기

In [1]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
import numpy as np
np.array([x for x in range(1,6)])

array([1, 2, 3, 4, 5])

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
# 실수형 데이터가 들어가면 모두 실수형으로 바뀜
np.array([3, 1.4, 2, 3, 4])

array([3. , 1.4, 2. , 3. , 4. ])

In [5]:
# 2차원 배열로 만듬
np.array([[1,2],
          [3,4]])

array([[1, 2],
       [3, 4]])

In [6]:
# dtype = 'float' 실수형태로 
np.array([1,2,3,4],dtype = 'float')

array([1., 2., 3., 4.])

배열 데이터 타입 dtype

In [16]:
arr = np.array([1,2,3,4], dtype = float)
arr # array([1., 2., 3., 4.])
arr.dtype # dtype('float64')
arr.astype(int) # array([1, 2, 3, 4])

array([1, 2, 3, 4])

Python List와 다르게 array는 단일 타입으로 구성된다.

배열 데이터 타입 dtype

dtype    설명      다양한 표현

int     정수형    i, int_, int32, int64,(=) i8
float   실수형    f, float32, float_,(=) float64, (=)f8
str     문자열    str, U, U32
bool    부울      ?, bool_

다양한 배열 만들기

In [17]:
# np.zeros 0 데이터를 가진 배열을 만듬
# 첫 번쨰 인자 데이터의 갯수 10
# 두 번째 인자 dtype = int # int형 데이터
np.zeros(10,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
# np.ones 데이터를 1로 채워서 만듬
# 첫 번째 인자 (3,5) # 3행 5열로 이루어진 2차원 배열을 만듬
# 두 번째 인자 dtype = float # float형 데이터
np.ones((3,5), dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
# np.arange() 파이썬의 range객체와 비슷함
# 0부터 20전까지 2개씩 (start, end, step)
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
# 0부터 1포함까지 5개로 나누어진 데이터를 만듬
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

난수로 채워진 배열 만들기

In [22]:
# 2행 2열로 이루어진 1보다 작은 실수로 이루어진 데이터
# shape = (2,2)
np.random.random((2,2))

array([[0.01495919, 0.27067973],
       [0.73532103, 0.70640667]])

In [23]:
# 정규분포로 데이터 추출
# 평균이 0이고 표준편차가 1인 데이터를
# shape (2, 2)
np.random.normal(0, 1, (2 ,2))

array([[ 1.14403796,  1.01966854],
       [ 0.21651225, -1.20956011]])

In [39]:
# 0부터 10까지 2,2형태로 출력
np.random.randint(0, 10, (2, 2))

array([[6, 9],
       [4, 6]])

In [40]:
# 배열 만들기
# Numpy 라이브러리는 효율적인 데이터분석이 가능하도록 N차원의 배열 객체를 지원합니다.

# Numpy의 배열은 파이썬의 list()보다도 빠른 연산과 효율적인 메모리 사용이 가능하기 때문에 빅데이터 분석 등에 널리쓰이는 매우 강력한 라이브러리라고 할 수 있습니다.

# 첫 실습으로 Numpy의 배열을 만들어 봅시다.

# Numpy library에서 자주 사용되는 함수
# np.array - 배열생성
# np.zeros - 0이 들어있는 배열 생성
# np.ones - 1이 들어있는 배열 생성
# np.empty - 초기화가 없는 값으로 배열을 반환
# np.arange(n) - 배열 버전의 range 함수
# np.random - 다양한 난수가 들어있는 배열 생성
# 예시
# 0이상 10 미만의 랜덤한 값이 들어있는 2*4크기의 배열을 변수 array에 저장합니다.
# array = np.random.randint(0,10,(2,4))
# Copy

# 지시사항
# 0 이상 5 미만의 랜덤한 값이 들어가 있는 3X5 배열을 만들어 array라는 배열

import numpy as np
#0부터 5사이 랜덤한 값이 담긴 3x5 array를 만들어 봅시다!
array = np.random.randint(0,5,(3,5))
print(array)

[[4 4 3 0 2]
 [3 3 1 1 4]
 [0 4 3 3 2]]


배열의 기초

In [46]:
#     numpy.random.randint 10미만  사이즈 3행 4열
x2 = np.random.randint(10, size=(3, 4),dtype = "int64")
print(x2) 
# ndim <- 차원이 몇차원인가?  2차원
print(x2.ndim) # 2
print(x2.shape) # (3, 4) 3행 4열
print(x2.size) # 12 개의 데이터를 가지고 있다
print(x2.dtype) # int64 # 데이터 타입은 int64이다.

[[9 3 6 8]
 [3 6 0 0]
 [2 8 1 4]]
2
(3, 4)
12
int64


찾고 잘라내기
Indexing : 인덱스로 값을 찾아낸다.
[0, 1, 2, 3, 4, 5, 6]

In [51]:
x = np.arange(7)
print(x) # [0 1 2 3 4 5 6]
print(x[3]) # 3
# print(x[7]) # IndexError: index 7 is out of bounds for axis 0 with size 7
x[0] = 10
print(x) # [10  1  2  3  4  5  6]

[0 1 2 3 4 5 6]
3
[10  1  2  3  4  5  6]


찾고 잘라내기
Slicing : 인덱스 값으로 배열의 부분을 가져오는 것
[0, 1, 2, 3, 4, 5, 6]

In [55]:
x = np.arange(7)
print(x[1:4]) # [1 2 3]
print(x[1:]) # [1 2 3 4 5 6]
print(x[:4]) # [0 1 2 3]
print(x[::2]) # [0 2 4 6]

[1 2 3]
[1 2 3 4 5 6]
[0 1 2 3]
[0 2 4 6]


배열의 기초
이전 실습에서 우리는 Numpy를 활용하여 배열을 생성해 보았습니다.

ndarray에는 배열의 여러 정보를 나타내는 속성값을 담고 있는데요, ndim, shape, size, dtype 등이 있습니다.

이번에는 배열의 다양한 속성들을 실습을 통해서 익혀봅시다.


지시사항
Q1

array의 자료형을 출력해보세요. type() 함수로 변수의 자료형을 구할 수 있습니다.

print(type(array))
이 type(array)의 의미는 array라는 변수가 파이썬에서 어떤 자료형으로 저장되고 있는지 알 수 있는 것입니다.

Q2

array의 차원을 출력해보세요.

print(array.ndim)
Q3

array의 모양을 출력해보세요.

print(array.shape)
Q4

array의 크기를 출력해보세요.

print(array.size)
Q5

array의 dtype을 출력해보세요. dtype이란, numpy 배열이 갖고 있는 요소의 자료형을 의미합니다.

print(array.dtype)
Q6

array의 인덱스 5의 요소를 출력해보세요.

print(array[5])
Q7

array의 인덱스 3의 요소부터 인덱스 5의 요소까지 출력해보세요.

print(array[3:6])

In [56]:
import numpy as np

print("1차원 array")
array = np.arange(10)
print(array)

# Q1. array의 자료형을 출력해보세요.
print(type(array))

# Q2. array의 차원을 출력해보세요.
print(array.ndim)

# Q3. array의 모양을 출력해보세요.
print(array.shape)

# Q4. array의 크기를 출력해보세요.
print(array.size)

# Q5. array의 dtype(data type)을 출력해보세요.
print(array.dtype)

# Q6. array의 인덱스 5의 요소를 출력해보세요.
print(array[5])

# Q7. array의 인덱스 3의 요소부터 인덱스 5 요소까지 출력해보세요.
print(array[3:6])


1차원 array
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
1
(10,)
10
int32
5
[3 4 5]


배열의 기초
이번 실습에서는 2차원 배열의 속성을 알아봅시다.

앞서 실습했던 1차원 배열의 속성과는 무엇이 다른지 비교하면서 ndarray의 속성값에 대해 자세히 알아봅시다.


지시사항
Q1

matrix의 자료형을 출력해보세요. type(matrix)로 자료형을 구할 수 있습니다.

print(type(matrix))
Q2

matrix의 차원을 출력해보세요.

print(matrix.ndim)
Q3

matrix의 모양을 출력해보세요.

print(matrix.shape)
Q4

matrix의 크기를 출력해보세요.

print(matrix.size)
Q5

matrix의 dtype을 출력해보세요.

print(matrix.dtype)
Q6

matrix의 인덱스 (2,3)번째 요소를 출력해보세요.

print(matrix[2,3])
Q7

matrix의 인덱스 (0,1)번째 요소부터 (1,3)번째 요소까지 출력해보세요.

print(matrix[0:2,1:4])

In [57]:
import numpy as np

print("2차원 array")
matrix = np.arange(1, 16).reshape(3,5)  #1부터 15까지 들어있는 (3,5)짜리 배열을 만듭니다.
print(matrix)


# Q1. matrix의 자료형을 출력해보세요.
print(type(matrix))

# Q2. matrix의 차원을 출력해보세요.
print(matrix.ndim)

# Q3. matrix의 모양을 출력해보세요.
print(matrix.shape)

# Q4. matrix의 크기를 출력해보세요.
print(matrix.size)

# Q5. matrix의 dtype(data type)을 출력해보세요.
print(matrix.dtype)

# Q6. matrix의 (2,3) 인덱스의 요소를 출력해보세요.
print(matrix[2,3])

# Q7. matrix의 행은 인덱스 0부터 인덱스 1까지, 열은 인덱스 1부터 인덱스 3까지 출력해보세요.
print(matrix[0:2,1:4])



2차원 array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
<class 'numpy.ndarray'>
2
(3, 5)
15
int32
14
[[2 3 4]
 [7 8 9]]


Reshape & 이어붙이고 나누기

모양 바꾸기
reshape : array의 shape를 변경한다.
[0 1 2 3 4 5 6 7]

[0 1 2 3]
[4 5 6 7]

In [59]:
import numpy as np
x = np.arange(8)
print(x) # [0 1 2 3 4 5 6 7]
print(x.shape) # (8,)
x2 = x.reshape((2,4))
print(x2)
# [[0 1 2 3]
# [4 5 6 7]]
print(x2.shape) # (2, 4)

[0 1 2 3 4 5 6 7]
(8,)
[[0 1 2 3]
 [4 5 6 7]]
(2, 4)


이어 붙이고 나누고
concatenate : array를 이어 붙인다.
[0 1 2] [3 4 5]
[0 1 2 3 4 5]

In [60]:
x = np.array([0, 1, 2])
y = np.array([3, 4, 5])
np.concatenate([x,y]) # array([0, 1, 2, 3, 4, 5])

array([0, 1, 2, 3, 4, 5])

이어 붙이고 나누고
np.concatenate : axis 축을 기준으로 이어 붙일 수 있다
[0 1]
[2 3]   

[0 1]
[2 3]
[0 1]
[2 3]

In [63]:
matrix = np.arange(4).reshape(2, 2)
matrix
# [[0 1]
# [2 3]]
np.concatenate([matrix, matrix], axis = 0) # 0 세로(열)
# array([[0, 1],
#       [2, 3],
#       [0, 1],
#       [2, 3]])
np.concatenate([matrix, matrix], axis = 1) # 1 가로(행)
# array([[0, 1, 0, 1],
#       [2, 3, 2, 3]])

[[0 1]
 [2 3]]


array([[0, 1, 0, 1],
       [2, 3, 2, 3]])

이어 붙이고 나누고
np.split : axis 축을 기준으로 나눌 수 있다
[ 0 1 2 3 ]
[ 4 5 6 7 ]
[ 8 9 10 11 ]
[ 12 13 14 15]

[0 1 2 3]
[4 5 6 7]
[8 9 10 11]

[12 13 14 15]

In [68]:
matrix = np.arange(16).reshape(4, 4)
print(matrix)
# [[ 0  1  2  3]
# [ 4  5  6  7]
# [ 8  9 10 11]
# [12 13 14 15]]
print("----------------")

upper, lower = np.split(matrix, [3], axis = 0)
print(upper)
# [[ 0  1  2  3]
# [ 4  5  6  7]
# [ 8  9 10 11]]
print("----------------")
print(lower)
# [[12 13 14 15]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
----------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
----------------
[[12 13 14 15]]


이어 붙이고 나누고
np.split : axis 축을 기준으로 나눌 수 있다
[ 0 1 2 3 ]
[ 4 5 6 7 ]
[ 8 9 10 11 ]
[ 12 13 14 15]

[0 1 2]    [3]
[4 5 6]    [7]
[8 9 10]   [11]
[12 13 14] [15]

In [73]:
matrix = np.arange(16).reshape(4, 4)
print(matrix)
# [[ 0  1  2  3]
# [ 4  5  6  7]
# [ 8  9 10 11]
# [12 13 14 15]]
print("===========")

left, right = np.split(matrix, [3], axis = 1)
print(left)
# [[ 0  1  2]
# [ 4  5  6]
# [ 8  9 10]
# [12 13 14]]
print("===========")
print(right)
# [[ 3]
# [ 7]
# [11]
# [15]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]
[[ 3]
 [ 7]
 [11]
 [15]]


이어 붙이고 나누기
array의 모양을 바꿔보는 reshape()함수에 대해 배워봅시다.

reshape()함수는 배열의 속성 중 하나인 shape를 변경할 수 있게 하는 함수입니다.

reshape() 함수를 사용하면 1차원 배열을 2차원 배열로 바꾸거나, 2차원 배열의 열과 행의 개수를 조절할 수 있습니다.


지시사항
주어진 array를 matrix라는 변수로 (2,4) 모양으로 reshape하여 저장하고 제출해보세요.

matrix와 matrix의 shape를 출력하여 array와 어떤 점이 다른지 살펴보세요.

In [74]:
import numpy as np

print("array")
array = np.arange(8)
print(array)
print("shape : ", array.shape, "\n")

# Q1. array를 (2,4) 크기로 reshape하여 matrix에 저장한 뒤 matrix와 그의 shape를 출력해보세요.
print("# reshape (2, 4)")
matrix = array.reshape((2,4))


print(matrix)
print("shape : ", matrix.shape)


array
[0 1 2 3 4 5 6 7]
shape :  (8,) 

# reshape (2, 4)
[[0 1 2 3]
 [4 5 6 7]]
shape :  (2, 4)


이어 붙이고 나누기
이번에는concatenate()함수를 이용하여 array를 서로 붙여보도록 하겠습니다.

concatenate() 함수로 두 배열과 붙이는 방향을 설정하여 하나의 배열로 만들 수 있습니다.

열의 개수가 같은 array끼리는 세로(axis 0)로 붙일 수 있고, 행의 개수가 같은 array끼리는 가로(axis 1)로 붙일 수 있습니다.


지시사항
Q1.

주어진 matrix 변수 두 개를 세로로 이어붙이고 m이란 변수에 저장하여 출력해보세요.

Q2.

주어진 matrix 변수 두 개를 가로로 이어붙이고 n이란 변수에 저장하여 출력해보세요.

In [75]:
import numpy as np

print("matrix")
matrix = np.array([[0,1,2,3],
                   [4,5,6,7]])
print(matrix)
print("shape : ", matrix.shape, "\n")

# (아래의 배열 모양을 참고하세요.)
# Q1. matrix 두 개를 세로로 붙이기 
'''
[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]]
'''
m = np.concatenate([matrix, matrix] ,axis = 0)
print(m)


# Q2. matrix 두 개를 가로로 붙이기
'''
[[0 1 2 3 0 1 2 3]
 [4 5 6 7 4 5 6 7]]
'''
n = np.concatenate([matrix, matrix], axis = 1)
print(n)



matrix
[[0 1 2 3]
 [4 5 6 7]]
shape :  (2, 4) 

[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3 0 1 2 3]
 [4 5 6 7 4 5 6 7]]


이어 붙이고 나누기
이번에는split() 함수를 이용하여 array를 axis를 기준으로 나누어보도록 하겠습니다.

앞서 실습해 본 concatenate() 함수와는 달리 split() 함수는 하나의 배열과 방향을 지정하여 두 개의 배열로 나누어줍니다.


지시사항
Q1.

주어진 matrix를 axis 0을 활용하여 3번째 행을 기준으로 나누고, 그 결과를 각각 a, b란 변수에 저장합시다.

a와 b를 각각 출력해보세요.

Q2.

주어진 matrix를 axis 1을 활용하여 1번째 열을 기준으로 나누고, 그 결과를 각각 c, d란 변수에 저장합시다.

c와 d를 각각 출력해보세요.

In [ ]:
import numpy as np

print("matrix")
matrix = np.array([[ 0, 1, 2, 3],
                   [ 4, 5, 6, 7],
                   [ 8, 9,10,11], 
                   [12,13,14,15]])
print(matrix, "\n")

# Q1. matrix를 [3] 행에서 axis 0으로 나누기
'''
[[0  1   2  3]
 [4  5   6  7]
 [8  9  10 11]],

 [12 13 14 15]
'''
a, b = np.split(matrix, [3], axis= 0)

print(a, "\n")
print(b, "\n")


# Q2. matrix를 [1] 열에서 axis 1로 나누기
'''
[[ 0]
 [ 4]
 [ 8]
 [12]],

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
'''

c, d = np.split(matrix, [1], axis = 1)

print(c, "\n")
print(d)


Numpy 연산

루프는 느리다
array의 모든 원소에 5를 더해서 만드는 함수

In [78]:
def add_five_to_array(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = values[i] + 5
    return output

values = np.random.randint(1, 10, size = 5)
print(values) # [6 8 9 1 3]
values = add_five_to_array(values)
print(values) # [11. 13. 14.  6.  8.]

[6 8 9 1 3]
[11. 13. 14.  6.  8.]


루프는 느리다
만약 array의 크기가 크다면..?

In [82]:
import time
big_array = np.random.randint(1,100, size = 10000000)
print(big_array)
# 함수 구현부
def add_five_to_array(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = values[i] + 5
    return output

# 함수로 시간 체크
start = time.time()
big_array = add_five_to_array(big_array)
end = time.time()
print(end - start)
print(big_array)

# array식 시간체크
start = time.time()
big_array = big_array + 5
end = time.time()
print(end-start)
print(big_array)

[ 7 82 24 ...  5 24 45]
4.426518678665161
[12. 87. 29. ... 10. 29. 50.]
0.02590775489807129
[17. 92. 34. ... 15. 34. 55.]


기본 연산
array는 +, -, *, / 에 대한 기본 연산을 지원한다

In [92]:
x = np.arange(4)
print(x) # [0 1 2 3]
x += 5
print(x) # [5 6 7 8]
x -= 5
print(x) # [0 1 2 3]
x *= 5
print(x) # [ 0  5 10 15]
x //= 5
print(x) # [0 1 2 3]
x *= 5
x = x / 5
print(x) # [0. 1. 2. 3.]

[0 1 2 3]
[5 6 7 8]
[0 1 2 3]
[ 0  5 10 15]
[0 1 2 3]
[0. 1. 2. 3.]


행렬간 연산
다차원 행렬에서도 적용가능하다.

In [93]:
x = np.arange(4).reshape((2,2))
y = np.random.randint(10, size =(2, 2))
print(x)
# [[0 1]
#  [2 3]]

print(y)
# [[9 1]
# [4 7]]

print(x+y)
# [[ 9  2]
#  [ 6 10]]

print(x-y)
# [[-9  0]
#  [-2 -4]]

[[0 1]
 [2 3]]
[[9 1]
 [4 7]]
[[ 9  2]
 [ 6 10]]
[[-9  0]
 [-2 -4]]


기본 연산
Numpy의 배열에는 기본 연산이 지원됩니다.

그리고 Numpy의 배열끼리도 연산을 수행할 수 있습니다.

Numpy로 생성한 배열을 가지고 배열과 숫자, 배열과 배열 사이의 사칙연산을 해봅시다.


문제
Q1.

array에 5를 더한 값을 출력하세요.

array + 5
Q2.

array에 5를 뺀 값을 출력하세요.

array - 5
Q3.

array에 5를 곱한 값을 출력하세요.

array * 5
Q4.

array를 5로 나눈 값을 출력하세요.

array / 5
Q5.

array에 array2를 더한 값을 출력하세요.

array + array2
Q6.

array에 array2를 뺀 값을 출력하세요.

array - array2

In [94]:
import numpy as np

array = np.array([1,2,3,4,5])
print(array)


# Q1. array에 5를 더한 값을 출력해보세요.
print(array + 5)

# Q2. array에 5를 뺀 값을 출력해보세요.
print(array - 5)

# Q3. array에 5를 곱한 값을 출력해보세요.
print(array * 5)

# Q4. array를 5로 나눈 값을 출력해보세요.
print (array / 5)


# Q5. array에 array2를 더한 값을 출력해보세요.    
array2 = np.array([5,4,3,2,1])
print(array + array2)


# Q6. array에 array2를 뺀 값을 출력해보세요.
print(array - array2)



[1 2 3 4 5]
[ 6  7  8  9 10]
[-4 -3 -2 -1  0]
[ 5 10 15 20 25]
[0.2 0.4 0.6 0.8 1. ]
[6 6 6 6 6]
[-4 -2  0  2  4]


브로드캐스팅

브로드캐스팅
Broadcasting : shape이 다른 array끼리 연산
          
            matrix + 5
           
   2  4  2                7  9  7
   6  5  9       5        11 10 14
   9  4  7                14  9 12

         matrix + np.array([1, 2, 3])

2   4   2                     3   6   5
6   5   9        1  2  3      7   7  12
9   4   7                     10  6  10

     np.arange(3).reshape((3,1)) + np.arange(3)

0                     0 1 2       0  1  2
1                                 1  2  3
2                                 2  3  4

브로드캐스팅
Numpy로 생성한 배열의 크기가 다를 경우 연산을 하게 되면 결과가 어떻게 출력될까요?

이럴경우 Numpy에서는 브로드캐스팅이라는 연산 방식으로 처리합니다.

아래의 출력 결과를 만들기 위해 지시사항을 따라 코딩해주세요.

출력 예시

[[ 0  1  2  3  4  5]
 [ 1  2  3  4  5  6]
 [ 2  3  4  5  6  7]
 [ 3  4  5  6  7  8]
 [ 4  5  6  7  8  9]
 [ 5  6  7  8  9 10]]

문제
[[0]
 [1]
 [2]
 [3]
 [4]

 [5]]
     
[0 1 2 3 4 5]
인 numpy 배열을 브로드캐스팅을 이용하여 덧셈하고 결과를 출력해봅시다!

두 배열의 변수 이름은 각각 A, B 여야 합니다.

예시
A = np.arange(6).reshape(6,1)
B = np.arange(6)
print(A+B)
모양이 다른 두 배열 A와 B를 덧셈 연산할 때 브로드캐스팅이 적용됩니다.

In [95]:
import numpy as np

'''
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]] 배열 A와

 [0 1 2 3 4 5] 배열 B를 선언하고, 덧셈 연산해보세요.
'''
A = np.arange(6).reshape((6,1))
B = np.arange(6)
print(A+B)

[[ 0  1  2  3  4  5]
 [ 1  2  3  4  5  6]
 [ 2  3  4  5  6  7]
 [ 3  4  5  6  7  8]
 [ 4  5  6  7  8  9]
 [ 5  6  7  8  9 10]]


집계함수 & 마스킹 연산

집계함수
집계 : 데이터에 대한 요약 통계를 볼 수 있다

In [103]:
x = np.arange(8).reshape((2,4))
print(x)
# [[0 1 2 3]
#  [4 5 6 7]]
print(np.sum(x))
# 28
print(np.min(x))
# 0
print(np.max(x))
# 7
print(np.mean(x))
# 3.5

# 표준편차
print(np.std(x))
# 2.29128784747792

print(np.sum(x, axis = 0))
# [ 4  6  8 10]

print(np.sum(x, axis = 1))
# [ 6, 22]

[[0 1 2 3]
 [4 5 6 7]]
28
0
7
3.5
2.29128784747792
[ 4  6  8 10]
[ 6 22]


마스킹 연산
마스킹 연산 : True, False array를 통해서
            특정 값을 뽑아내는 방법

In [108]:
x = np.arange(5)
print(x) # [0 1 2 3 4]

print(x<3) # [ True  True  True False False]

print(x>5) # [False False False False False]

print(x[x < 3]) # [0 1 2]

[0 1 2 3 4]
[ True  True  True False False]
[False False False False False]
[0 1 2]


집계함수 & 마스킹연산
집계함수 sum(), min(), max(), mean() 등을 활용하여 배열에 있는 요약 통계를 확인해 봅시다.

이 집계함수들은 numpy 패키지 안에 있으며, 함수 안에 배열 이름을 넣으면 해당 배열의 요약 통계량을 구할 수 있습니다.

마스킹 연산은 조건식을 통해 배열에서 원하는 값을 추출할 수 있습니다.

집계함수 와 마스킹연산은 함께 활용되는 일이 많으니 잘 알아두셔야 합니다.


문제
Q1.

sum 함수로 matrix의 총 합계를 구해 출력해보세요.

np.sum(matrix)
Q2.

max 함수로 matrix 중 최댓값을 구해 출력해보세요.

np.max(matrix)
Q3.

min 함수로 matrix 중 최솟값을 구해 출력해보세요.

np.min(matrix)
Q4.

mean 함수로 matrix의 평균값을 구해 출력해보세요.

np.mean(matrix)
Q5.

sum 함수의 axis 매개변수로 각 열의 합을 구해 출력해보세요.

np.sum(matrix, axis=0)
Q6.

sum 함수의 axis 매개변수로 각 행의 합을 구해 출력해보세요.

np.sum(matrix, axis=1)
Q7.

std 함수로 matrix의 표준편차를 구해 출력해보세요.

np.std(matrix)
Q8.

마스킹 연산을 이용하여 matrix 중 5보다 작은 수들만 추출하여 출력해보세요.

print(matrix[matrix<5])

In [109]:
import numpy as np

matrix = np.arange(8).reshape((2, 4))
print(matrix)

# Q1. sum 함수로 matrix의 총 합계를 구해 출력해보세요.
print(np.sum(matrix))

# Q2. max 함수로 matrix 중 최댓값을 구해 출력해보세요.
print(np.max(matrix))

# Q3. min 함수로 matrix 중 최솟값을 구해 출력해보세요.
print(np.min(matrix))

# Q4. mean 함수로 matrix의 평균값을 구해 출력해보세요.
print(np.mean(matrix))

# Q5. sum 함수의 axis 매개변수로 각 열의 합을 구해 출력해보세요.
print(np.sum(matrix, axis = 0))

# Q6. sum 함수의 axis 매개변수로 각 행의 합을 구해 출력해보세요.
print(np.sum(matrix, axis = 1))


# Q7. std 함수로 matrix의 표준편차를 구해 출력해보세요.
print(np.std(matrix))


# Q8. 마스킹 연산을 이용하여 matrix 중 5보다 작은 수들만 추출하여 출력해보세요.
print(matrix[matrix<5])

[[0 1 2 3]
 [4 5 6 7]]
28
7
0
3.5
[ 4  6  8 10]
[ 6 22]
2.29128784747792
[0 1 2 3 4]


배열의 황제! Numpy
고성능의 수치 계산을 위해 만들어진 라이브러리
Numpy

Numpy가 널리쓰이고 강력하다는 말을 듣게 해주는 것은 바로 ndarry의 힘이라고 봐도 과언이 아닙니다.

numpy 라이브러리는 효율적인 데이터분석이 가능하도록 N차원의 배열 객체를 지원합니다.

numpy library에서 자주 사용되는 함수들로는

np.array - 배열생성
np.zeros - 0이 들어있는 배열 생성
np.ones - 1이 들어있는 배열 생성
np.empty - 초기화되어 있지 않은 값이 들어있는 배열 반환
np.arange(n) - 배열 버전의 range 함수

가 있습니다.